spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 11539140822-cbmckcrgi6bp67o86vat84acgkrqi5vp.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/auth/oauth2/google
            scope:
              - profile
              - email