spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 11539140822-c9a3eui7tel6cgmumnrh2kic7llmp17n.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email