version: "3"
services:
  application:
    build:
      context: ./backend/tiggle-root
      dockerfile: Dockerfile.tiggle
    restart: always
    ports:
      - "8080:8080"
    container_name: tiggle_app
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tiggle.duckdns.org:3307/tiggle?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tiggle2024!#
      OAUTH2_GOOGLE_CLIENT_ID: 39538605611-murngjhufa3alnvqcuil4qr86oalf5as.apps.googleusercontent.com
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_KAKAO_CLIENT_ID: 5d4367700d9f4536fbb76582403e80eb
      OAUTH2_KAKAO_CLIENT_SECRET: 0dsuAWhu33cAQcZL2Njh5ZKtq8BJqxIq
      OAUTH2_NAVER_CLIENT_ID: bIMfzZ1Ct5UpwVgF4tep
      OAUTH2_NAVER_CLIENT_SECRET: ISy4u_NWcP
  notification:
    build:
      context: ./backend/tiggle-root
      dockerfile: Dockerfile.noti
    restart: always
    ports:
      - "8082:8082"
    container_name: tiggle_noti
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tiggle.duckdns.org:3307/tiggle?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tiggle2024!#
      KAFKA_URL: kafka:29092
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge
