name: Deploy to NAS Server

on:
  push:
    branches: [ main ]

jobs:     
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ssh connect & docker compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            export PATH="$PATH:/usr/local/bin"
            cd Tiggle
            ./server.sh
