name: Deploy to NAS Server

on:
  push:
    branches: [ main ]

jobs:     
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: ssh connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git pull origin main
            cd Tiggle
            export PATH="$PATH:/usr/local/bin"
            ./server.sh
