name: Deploy to NAS Server

on:
  push:
    branches: [ main, be-feat/v2-build-test ]

jobs:     
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ssh connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: |
          git pull -f origin be-feat/v2-build-test
          git checkout be-feat/v2-build-test
        # run: git pull origin main
      
      - name: Run server.sh
        run: |
          pwd
          ls -al
          export PATH="$PATH:/usr/local/bin"
          sudo ./server.sh
